project:
  type: book

book:
  title: "SysLit Compendium"
  author: "Marc von Gernler"
  date: 04/24/2024
  chapters:
    - index.qmd
    - databases.qmd
    - technicalterms.qmd
    - tools.qmd
    - methods.qmd
    - references.qmd

bibliography: glossar.bib

format:
  html:
    theme: united
  pdf:
    documentclass: scrreprt



