project:
  type: book
  output-dir: docs

book:
  title: "SysLit Compendium"
  subtitle: "a candle in the dark"
  author: "Marc von Gernler"
  description: A compendium for systematic literature searching
  keyword: systematic searching, information retrieval, bibliographic databases, evidence-based medicine
  cover-image: ./fig/logo_2.svg
  chapters:
    - index.qmd
    - databases.qmd
    - technicalterms.qmd
    - tools.qmd
    - methods.qmd
    - publicationtypes.qmd
    - references.qmd
  navbar:
    logo: ./fig/logo_small.svg
    background: "#2a536b" 
  search:
    location: sidebar
    type: textbox
  repo-url: https://www.github.com/Maelphes/syslitcom
  repo-branch: gh-pages
  repo-actions: [edit, issue, source]

bibliography: glossar.bib

format:
  html:
    theme: united
    link-external-newwindow: true
    linkcolor: "#5080AA"
  pdf:
    documentclass: scrreprt



