project:
  type: book
  output-dir: docs

book:
  title: "SysLit Compendium"
  author: "Marc von Gernler"
  date: 04/24/2024
  cover-image: ./fig/logo.svg
  chapters:
    - index.qmd
    - databases.qmd
    - technicalterms.qmd
    - tools.qmd
    - methods.qmd
    - references.qmd

bibliography: glossar.bib

format:
  html:
    theme: united
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt



