project:
  type: book
  output-dir: docs

book:
  title: "SysLit Compendium"
  subtitle: "a candle in the dark"
  author: "Marc von Gernler"
  date: 04/24/2024
  cover-image: ./fig/logo.svg
  chapters:
    - index.qmd
    - databases.qmd
    - technicalterms.qmd
    - tools.qmd
    - methods.qmd
    - references.qmd
  navbar:
    search: true
    logo: ./fig/logo_small.svg
  search:
    location: sidebar
    type: textbox

bibliography: glossar.bib

format:
  html:
    theme: united
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt



