---
format: html
code-fold: false
link-citations: true
link-bibliography: true
filters:
  - parse-latex
---

# Tools {#sec-tools}

## Entrez Programming Utilities {#sec-e-utilities}

The **Entrez Programming Utilities** (E-utilities) are a set of nine 
programs which provide an [API](https://en.wikipedia.org/wiki/API) to the 
[Entrez](#sec-entrez) database system of the NCBI. Comprehensive information 
about the E-utilifies is available in the official 
[E-utilities Help](https://www.ncbi.nlm.nih.gov/books/NBK25501/).

### E-utilities via URL
These programs are server-based and can be deployed using different URLs.
These URLs to query Entrez are composed of the base URL `https://eutils.ncbi.nlm.nih.gov/entrez/eutils/`
to which a string with the desired utility and the query is attached, for instance 
[`esearch.fcgi?db=pubmed&term=BMJ[journal]+AND+hernia+AND+2010[pdat]`](https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=BMJ[journal]+AND+hernia+AND+2010[pdat])

The results for these queries are usually returned as XML-structured data.

### Entrez Direct

The E-utilities are also available directly on a [Unix shell](https://en.wikipedia.org/wiki/Unix_shell) under Linux or macOS by using the package [**Entrez Direct**](https://www.ncbi.nlm.nih.gov/books/NBK179288/) (EDirect). 

One of the main advantages of EDirect are the [commands](https://www.freecodecamp.org/news/the-linux-commands-handbook/) that are available on the shell, for example `grep`, `sort`, `uniq` or `wc`, 
which allow the results to be processed directly. Also shell scripts can be used
to automate the processing.

:::{.callout-tip title="Example: Retrieve similar articles"}
The command 

```
elink -db pubmed -id 25554246,29463298 -related -cmd neighbor | 
xtract -pattern LinkSetDb -element Id
```

will return all [PMIDs](#sec-pmid-pmcid) of publications which PubMed identifies
as [*Similar Articles*](https://pubmed.ncbi.nlm.nih.gov/help/#similar-articles) 
for the PMIDs [25554246](https://pubmed.ncbi.nlm.nih.gov/?linkname=pubmed_pubmed&from_uid=25554246) 
and  [29463298](https://pubmed.ncbi.nlm.nih.gov/?linkname=pubmed_pubmed&from_uid=29463298).

On PubMed the Similar Articles search can be carried out for only one PMID at a
time, whereas using the E-utilities it is possible to search with many PMIDs in
a single query.
:::

:::{.callout-tip title="Unix Shell on Windows" collapse=true}
There is a quick and easy way to get access to Linux and its shell even when
one is running a modern Windows PC: The Windows Subsystem for Linux (WSL) 
provides an environment to install Linux from within Windows (10 or later).

For more on this, see

- [How to install Linux on Windows with WSL](https://learn.microsoft.com/en-us/windows/wsl/install)  
- [Library Carpentry: The Unix Shell](https://librarycarpentry.org/lc-shell/)  
:::

## FINER {#sec-finer}
FINER is an acronym for the five criteria **feasible**, **interesting**, **novel**, **ethical** and **relevant** which can be used as guidance when formulating a good clinical research question. See @tbl-finer. (@Cummings2013)


::: {#tbl-finer}
```{=latex}
\begin{table*}[!ht]
  \begin{tabular}{l p{7.8cm}}
    \toprule
    \textbf{Criterion} & \textbf{Meaning}\\
    \midrule
feasible & The research question should not exceed the available resources, i.e.\ participants, expertise, time and money). \\
interesting & The research question should in itself be interesting, not only to the researcher, but also to a broader public. \\
novel & The gain of knowledge and new information should be at the heart of the question. Research usually does not only reiterate already established data unless it is designed as a confirmatory study. \\
ethical & Proper research has to be ethical and must not bear unacceptable risks for its participants. \\
relevant & The expected impact of the research on scientific knowledge and clinical processes can be a good measurement parameter for the relevance. \\
		\bottomrule
  \end{tabular}
\end{table*}
```
:::

## PICO {#sec-pico}
PICO is a mnemonic for the concepts *Population*, *Intervention*, *Comparison* 
and *Outcome*. Concepts like these are used for defining research questions as 
well as eligibility criteria for the studies relevant for answering the 
question.

There are other concepts and mnemonics for different kinds of research 
questions, such as SPIDER, ECLIPSE, PIRD or PICOS. (@Munn2018a, @Methley2014, 
@Eriksen2018)

## PRESS {#sec-press}
**Peer Review of Electronic Search Strategies (PRESS)** by @McGowan2016 is an 
evidence-based guideline for the peer review of search strategies. It is mainly 
focused on systematic review projects, health technology assesments (HTAs) and 
other kinds of reviews. A main tool for PRESS is a checklist which guides the 
reader through the process of peer review.

## PRISMA {#sec-prisma}

**Preferred Reporting Items for Systematic Reviews and Meta-Analyses (PRISMA)**
by @Page2021a is a set of minimum requirements for the reporting and 
documentation of systematic reviews. The goal of PRISMA is to set standards for
reporting and in doing so increase the overall quality of systematic reviews. 
A detailed explanatory paper was published by @Page2021b.

PRISMA also provides tools such as a checklist and a flowchart, which can be 
used for creating the recommended tables and figures for publication. 
(@rethlefsen_page_2021)

There are additional extensions of PRISMA for various purposes, such as 
PRISMA-S for the documentation of systematic literature searches 
(@Rethlefsen2021) or PRISMA-ScR for scoping reviews (@Tricco2018).

See also <https://prisma-statement.org>.


## Reference Management software {#sec-refmanagement}
Bibliographic records and similar sets of data such as clinical study metadata 
can be stored and managed using **reference management programs** (also called 
citation management software). 

These programs are usually able to perform tasks with the records, such as

- import and export of various formats (e.g. RIS, NBIB, BIB, TXT, CSV, XML)
- creation, editing and updating
- deduplication
- retrieval of full-texts
- output of citations in various styles

::: {.callout-tip title="Examples of reference managers" collapse="true"} 
- [Citavi](https://www.citavi.com)
- [EndNote](https://www.endnote.com)
- [JabRef](https://www.jabref.org)
- [Mendeley](https://www.mendeley.com)
- [Zotero](https://www.zotero.org)
:::
For comparisons of reference management software see also <https://mediatum.ub.tum.de/1320978> and <https://en.wikipedia.org/wiki/Comparison_of_reference_management_software>.